package pojo;
// Generated Sep 26, 2024 8:20:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Integer commentId;
     private Courses courses;
     private Users users;
     private String comment;
     private String username;
     private Integer rating;
     private Date createdAt;

    public Comments() {
    }

	
    public Comments(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Comments(Courses courses, Users users, String comment, String username, Integer rating, Date createdAt) {
       this.courses = courses;
       this.users = users;
       this.comment = comment;
       this.username = username;
       this.rating = rating;
       this.createdAt = createdAt;
    }
   
    public Integer getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Integer getRating() {
        return this.rating;
    }
    
    public void setRating(Integer rating) {
        this.rating = rating;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


