package pojo;
// Generated Sep 26, 2024 8:20:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Courses generated by hbm2java
 */
public class Courses  implements java.io.Serializable {


     private Integer courseId;
     private String title;
     private String description;
     private Set progresses = new HashSet(0);
     private Set commentses = new HashSet(0);
     private Set purchasedCourses = new HashSet(0);
     

    public Courses() {
    }

	
    public Courses(String title) {
        this.title = title;
    }
    public Courses(String title, String description, Set progresses, Set commentses, Set purchasedCourses) {
       this.title = title;
       this.description = description;
       this.progresses = progresses;
       this.commentses = commentses;
       this.purchasedCourses = purchasedCourses;
    }
   
    public Integer getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getProgresses() {
        return this.progresses;
    }
    
    public void setProgresses(Set progresses) {
        this.progresses = progresses;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }
    public Set getPurchasedCourses() {
        return this.purchasedCourses;
    }
    
    public void setPurchasedCourses(Set purchasedCourses) {
        this.purchasedCourses = purchasedCourses;
    }




}


