package pojo;
// Generated Sep 26, 2024 8:20:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Progress generated by hbm2java
 */
public class Progress  implements java.io.Serializable {


     private Integer progressId;
     private Courses courses;
     private Users users;
     private Integer progressPercentage;
     private Date lastAccessed;

    public Progress() {
    }

	
    public Progress(Date lastAccessed) {
        this.lastAccessed = lastAccessed;
    }
    public Progress(Courses courses, Users users, Integer progressPercentage, Date lastAccessed) {
       this.courses = courses;
       this.users = users;
       this.progressPercentage = progressPercentage;
       this.lastAccessed = lastAccessed;
    }
   
    public Integer getProgressId() {
        return this.progressId;
    }
    
    public void setProgressId(Integer progressId) {
        this.progressId = progressId;
    }
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Integer getProgressPercentage() {
        return this.progressPercentage;
    }
    
    public void setProgressPercentage(Integer progressPercentage) {
        this.progressPercentage = progressPercentage;
    }
    public Date getLastAccessed() {
        return this.lastAccessed;
    }
    
    public void setLastAccessed(Date lastAccessed) {
        this.lastAccessed = lastAccessed;
    }




}


