package pojo;
// Generated Sep 26, 2024 8:20:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PurchasedCourse generated by hbm2java
 */
public class PurchasedCourse  implements java.io.Serializable {


     private Integer id;
     private Courses courses;
     private Users users;
     private Date purchaseDate;

    public PurchasedCourse() {
    }

	
    public PurchasedCourse(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }
    public PurchasedCourse(Courses courses, Users users, Date purchaseDate) {
       this.courses = courses;
       this.users = users;
       this.purchaseDate = purchaseDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getPurchaseDate() {
        return this.purchaseDate;
    }
    
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }




}


